version: '3.3'

services:
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    env_file:
      - ".env"
    ports:
      - "3306:3306"
    tty: true

  id_service:
    container_name: id_service
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "7001:7001"
    env_file:
      - ".env"
    tty: true
    depends_on:
      - mysql
