version: '3.3'

services:
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    env_file:
      - ".env"
    ports:
      - "3307:3306"
    tty: true
    networks:
      - appmysql

  id_service:
    container_name: id_service
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "7001:7001"
    tty: true
    depends_on:
      - mysql
    networks:
      - appmysql
networks:
  appmysql:
    driver: bridge